### ISSUE TITLE
pint ureg

### ISSUE THREAD

**Issue by andrewgsavage** [dylanwal/unit_parse#15]
from the readme:
```
import pint

u = pint.UnitRegistry()
U = Unit = u.Unit
Q = Quantity = u.Quantity

from unit_parse import parser

# your code from here…
```

Are you aware of pint's application registry? it was made for this purpose.
```
pint.set_application_registry(u)
pint.get_application_registry() # returns u
```

**Comment by dylanwal** [comment]
I was not aware. I did some looking at the docs and their use is still not clear to me. 

Can I use `pint.get_application_registry()` in my 'unit_parse' package to get a registry that has already been defined (or get new one if none have been previously defined)?

**Comment by andrewgsavage** [comment]
> Can I use `pint.get_application_registry()` in my 'unit_parse' package to get a registry that has already been defined (or get new one if none have been previously defined)?

yes
